### ISSUE TITLE
How to integrate esptool-ftdi with VSCODE?

### ISSUE THREAD

**Issue by hoffberg** [jimparis/esptool-ftdi#2]
As a newbie to VSCODE and ESP32 programming, I 'boy this is crazy that I have swap jumpers' on my board in order to program it.  After a bit of digging, I came across this package, which I believe provides the exact workaround that I was looking for (original reference: [https://www.esp32.com/viewtopic.php?t=6113](https://www.esp32.com/viewtopic.php?t=6113)).

I hate to bother you with this: I have spent some time trying to figure out how to change the VSCODE tool chain path with little luck.  Do you have any pointers as to where I should start looking?

**Comment by jimparis** [comment]
I don't know how vscode invokes esptool.  Wherever that is configured, you should be able to modify the commandline to put a `esptool-ftdi.py` in front of the `esptool.py` invocation.

Alternately, you could rename the original `esptool.py` and to put this `esptool-ftdi.py` script in its place, with a hardcoded path to the original script (instead of passing it on the command line).

**Comment by jimparis** [comment]
Another solution is to use the new `ESPTOOL_WRAPPER` environment variable as described [here](https://github.com/jimparis/esptool-ftdi/#integrating-with-esp-idf)
