### ISSUE TITLE
ESP32 - Write flash command causing (RTCWDT_RTC_RESET) error on startup

### ISSUE THREAD

**Issue by rtking1993** [jimparis/esptool-ftdi#7]
Hello,

First of all can I say a huge thank you for creating this piece of software. It is an absolute life saver as it has allowed me to connect my custom ESP32 board with my Tag Connect cable (https://www.tag-connect.com/product/tc2030-ftdi-ttl-232r-usb-to-tc2030-serial-cable).

I am able to successfully able to finish flashing the board, using the following command:
`./esptool-ftdi.py esptool.py --baud 115200 write_flash --flash_mode qio --flash_size 4MB 0x1000 AQ_Board.ino.esp32.bin
`
However upon starting the board, in the serial monitor I am only able to see repeating logs:
```
12:31:04.730 -> rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
12:31:04.767 -> configsip: 0, SPIWP:0xee
12:31:04.767 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
12:31:04.767 -> mode:QIO, clock div:2
12:31:04.767 -> load:0x3f400020,len:161780
12:31:05.095 -> ets Jun  8 2016 00:22:57
```

This is area is not my expertise, so I am unable to work out whether this is an issue with the software or most likely my own user error. Are you able to offer any advice?

Kind regards, Ryan

**Comment by jimparis** [comment]
I think this is likely unrelated to `esptool-ftdi`, if you're not seeing any errors during the flashing process.  I'd suggest asking at https://esp32.com or searching through threads there for `RTCWDT_RTC_RESET` -- it seems this may be due to incorrectly set flash voltages or similar.  e.g. https://esp32.com/viewtopic.php?t=25729
